// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: ProjectLightblub

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_HomeScreen
void ui_HomeScreen_screen_init(void);
lv_obj_t * ui_HomeScreen;
lv_obj_t * ui_HomeScreen_ContentContainer;
lv_obj_t * ui_HomeScreen_LightbulbPanel;
lv_obj_t * ui_HomeScreen_LightbulbLabel;
lv_obj_t * ui_HomeScreen_Container4;
lv_obj_t * ui_HomeScreen_LightbulbStatusLed;
void ui_event_HomeScreen_LightbulbManualSwitch(lv_event_t * e);
lv_obj_t * ui_HomeScreen_LightbulbManualSwitch;
lv_obj_t * ui_HomeScreen_LightblubStateLabel;
lv_obj_t * ui_HomeScreen_Container6;
lv_obj_t * ui_HomeScreen_TimePanel;
lv_obj_t * ui_HomeScreen_TimeLabel;
lv_obj_t * ui_HomeScreen_DateContainer;
lv_obj_t * ui_HomeScreen_WeekDayLabel;
lv_obj_t * ui_HomeScreen_DateLabel;
lv_obj_t * ui_HomeScreen_OverridePanel;
lv_obj_t * ui_HomeScreen_OverrideLabel;
void ui_event_HomeScreen_OverrideSwitch(lv_event_t * e);
lv_obj_t * ui_HomeScreen_OverrideSwitch;
lv_obj_t * ui_HomeScreen_OverrideStateLabel;
lv_obj_t * ui_HomeScreen_TitlePanel;
lv_obj_t * ui_HomeScreen_WifiStatusContainer;
lv_obj_t * ui_HomeScreen_WifiOnImage;
lv_obj_t * ui_HomeScreen_WifiOffImage;
lv_obj_t * ui_HomeScreen_TitleLabel;
void ui_event_HomeScreen_OptionButton(lv_event_t * e);
lv_obj_t * ui_HomeScreen_OptionButton;
lv_obj_t * ui_HomeScreen_OptionLabel;


// SCREEN: ui_SettingScreen
void ui_SettingScreen_screen_init(void);
lv_obj_t * ui_SettingScreen;
lv_obj_t * ui_SettingScreen_TitlePabel;
lv_obj_t * ui_SettingScreen_TitleLabel;
lv_obj_t * ui_SettingScreen_ContentContainer;
void ui_event_SettingScreen_WifiSSIDPanel(lv_event_t * e);
lv_obj_t * ui_SettingScreen_WifiSSIDPanel;
lv_obj_t * ui_SettingScreen_WifiSSIDLabel;
lv_obj_t * ui_SettingScreen_WifiSSIDMarkImage;
lv_obj_t * ui_SettingScreen_WifiSSIDNextImage;
void ui_event_SettingScreen_WifiPasswordPanel(lv_event_t * e);
lv_obj_t * ui_SettingScreen_WifiPasswordPanel;
lv_obj_t * ui_SettingScreen_WifiPasswordLabel;
lv_obj_t * ui_SettingScreen_WifiPasswordMarkImage;
lv_obj_t * ui_SettingScreen_WifiPasswordNextImage;
void ui_event_SettingScreen_GpsLatitudePanel(lv_event_t * e);
lv_obj_t * ui_SettingScreen_GpsLatitudePanel;
lv_obj_t * ui_SettingScreen_GpsLatitudeLabel;
lv_obj_t * ui_SettingScreen_GpsLatitudeMarkImage;
lv_obj_t * ui_SettingScreen_GpsLatitudeNextImage;
void ui_event_SettingScreen_GpsLongitudePanel(lv_event_t * e);
lv_obj_t * ui_SettingScreen_GpsLongitudePanel;
lv_obj_t * ui_SettingScreen_GpsLongitudeLabel;
lv_obj_t * ui_SettingScreen_GpsLongitudeMarkImage;
lv_obj_t * ui_SettingScreen_GpsLongitudeNextImage;
void ui_event_SettingScreen_RelayOffDelayPanel(lv_event_t * e);
lv_obj_t * ui_SettingScreen_RelayOffDelayPanel;
lv_obj_t * ui_SettingScreen_RelayOffDelayLabel;
lv_obj_t * ui_SettingScreen_RelayOffDelayMarkImage;
lv_obj_t * ui_SettingScreen_RelayOffDelayNextImage;
void ui_event_SettingScreen_RelayOnDelayPanel(lv_event_t * e);
lv_obj_t * ui_SettingScreen_RelayOnDelayPanel;
lv_obj_t * ui_SettingScreen_RelayOnDelayLabel;
lv_obj_t * ui_SettingScreen_RelayOnDelayMarkImage;
lv_obj_t * ui_SettingScreen_RelayOnDelayNextImage;
lv_obj_t * ui_SettingScreen_ActionPanel;
void ui_event_SettingScreen_BackButton(lv_event_t * e);
lv_obj_t * ui_SettingScreen_BackButton;
lv_obj_t * ui_SettingScreen_BackLabel;
void ui_event_SettingScreen_ResetButton(lv_event_t * e);
lv_obj_t * ui_SettingScreen_ResetButton;
lv_obj_t * ui_SettingScreen_Label6;
void ui_event_SettingScreen_ConfirmButton(lv_event_t * e);
lv_obj_t * ui_SettingScreen_ConfirmButton;
lv_obj_t * ui_SettingScreen_Label8;


// SCREEN: ui_KeyboardInputScreen
void ui_KeyboardInputScreen_screen_init(void);
lv_obj_t * ui_KeyboardInputScreen;
lv_obj_t * ui_KeyboardInputScreen_TitlePabel1;
lv_obj_t * ui_KeyboardInputScreen_TitleLabel;
lv_obj_t * ui_KeyboardInputScreen_Container3;
lv_obj_t * ui_KeyboardInputScreen_TextArea1;
lv_obj_t * ui_KeyboardInputScreen_Keyboard1;
lv_obj_t * ui_KeyboardInputScreen_ActionPanel1;
void ui_event_KeyboardInputScreen_BackButton1(lv_event_t * e);
lv_obj_t * ui_KeyboardInputScreen_BackButton1;
lv_obj_t * ui_KeyboardInputScreen_Label4;
void ui_event_KeyboardInputScreen_ResetButton(lv_event_t * e);
lv_obj_t * ui_KeyboardInputScreen_ResetButton;
lv_obj_t * ui_KeyboardInputScreen_Label5;
void ui_event_KeyboardInputScreen_ConfirmButton(lv_event_t * e);
lv_obj_t * ui_KeyboardInputScreen_ConfirmButton;
lv_obj_t * ui_KeyboardInputScreen_Label2;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_HomeScreen_LightbulbManualSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        toggleManualControl(e);
    }
}
void ui_event_HomeScreen_OverrideSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        toggleControlOverride(e);
    }
}
void ui_event_HomeScreen_OptionButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        toOptionPage(e);
    }
}
void ui_event_SettingScreen_WifiSSIDPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        prepareWifiSSIDToInput(e);
    }
}
void ui_event_SettingScreen_WifiPasswordPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        prepareWifiPasswordToInput(e);
    }
}
void ui_event_SettingScreen_GpsLatitudePanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        prepareGpsLatitudeToInput(e);
    }
}
void ui_event_SettingScreen_GpsLongitudePanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        prepareGpsLongitudeToInput(e);
    }
}
void ui_event_SettingScreen_RelayOffDelayPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        prepareRelayOffDelayToInput(e);
    }
}
void ui_event_SettingScreen_RelayOnDelayPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        prepareRelayOnDelayToInput(e);
    }
}
void ui_event_SettingScreen_BackButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        cancelNewSetting(e);
    }
}
void ui_event_SettingScreen_ResetButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        resetNewSettings(e);
    }
}
void ui_event_SettingScreen_ConfirmButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_HomeScreen_screen_init);
        applyNewSettings(e);
    }
}
void ui_event_KeyboardInputScreen_BackButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        cancelCurrentInput(e);
    }
}
void ui_event_KeyboardInputScreen_ResetButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        resetCurrentInput(e);
    }
}
void ui_event_KeyboardInputScreen_ConfirmButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SettingScreen_screen_init);
        applyCurrentInputToSetting(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_HomeScreen_screen_init();
    ui_SettingScreen_screen_init();
    ui_KeyboardInputScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_HomeScreen);
}
