// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: ProjectLightblub

#ifndef _PROJECTLIGHTBLUB_UI_H
#define _PROJECTLIGHTBLUB_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

// SCREEN: ui_HomeScreen
void ui_HomeScreen_screen_init(void);
extern lv_obj_t * ui_HomeScreen;
extern lv_obj_t * ui_HomeScreen_ContentContainer;
extern lv_obj_t * ui_HomeScreen_LightbulbPanel;
extern lv_obj_t * ui_HomeScreen_LightbulbLabel;
extern lv_obj_t * ui_HomeScreen_Container4;
extern lv_obj_t * ui_HomeScreen_LightbulbStatusLed;
void ui_event_HomeScreen_LightbulbManualSwitch(lv_event_t * e);
extern lv_obj_t * ui_HomeScreen_LightbulbManualSwitch;
extern lv_obj_t * ui_HomeScreen_LightblubStateLabel;
extern lv_obj_t * ui_HomeScreen_Container6;
extern lv_obj_t * ui_HomeScreen_TimePanel;
extern lv_obj_t * ui_HomeScreen_TimeLabel;
extern lv_obj_t * ui_HomeScreen_DateContainer;
extern lv_obj_t * ui_HomeScreen_WeekDayLabel;
extern lv_obj_t * ui_HomeScreen_DateLabel;
extern lv_obj_t * ui_HomeScreen_OverridePanel;
extern lv_obj_t * ui_HomeScreen_OverrideLabel;
void ui_event_HomeScreen_OverrideSwitch(lv_event_t * e);
extern lv_obj_t * ui_HomeScreen_OverrideSwitch;
extern lv_obj_t * ui_HomeScreen_OverrideStateLabel;
extern lv_obj_t * ui_HomeScreen_TitlePanel;
extern lv_obj_t * ui_HomeScreen_WifiStatusContainer;
extern lv_obj_t * ui_HomeScreen_WifiOnImage;
extern lv_obj_t * ui_HomeScreen_WifiOffImage;
extern lv_obj_t * ui_HomeScreen_TitleLabel;
void ui_event_HomeScreen_OptionButton(lv_event_t * e);
extern lv_obj_t * ui_HomeScreen_OptionButton;
extern lv_obj_t * ui_HomeScreen_OptionLabel;
// SCREEN: ui_SettingScreen
void ui_SettingScreen_screen_init(void);
extern lv_obj_t * ui_SettingScreen;
extern lv_obj_t * ui_SettingScreen_TitlePabel;
extern lv_obj_t * ui_SettingScreen_TitleLabel;
extern lv_obj_t * ui_SettingScreen_ContentContainer;
void ui_event_SettingScreen_WifiSSIDPanel(lv_event_t * e);
extern lv_obj_t * ui_SettingScreen_WifiSSIDPanel;
extern lv_obj_t * ui_SettingScreen_WifiSSIDLabel;
extern lv_obj_t * ui_SettingScreen_WifiSSIDMarkImage;
extern lv_obj_t * ui_SettingScreen_WifiSSIDNextImage;
void ui_event_SettingScreen_WifiPasswordPanel(lv_event_t * e);
extern lv_obj_t * ui_SettingScreen_WifiPasswordPanel;
extern lv_obj_t * ui_SettingScreen_WifiPasswordLabel;
extern lv_obj_t * ui_SettingScreen_WifiPasswordMarkImage;
extern lv_obj_t * ui_SettingScreen_WifiPasswordNextImage;
void ui_event_SettingScreen_GpsLatitudePanel(lv_event_t * e);
extern lv_obj_t * ui_SettingScreen_GpsLatitudePanel;
extern lv_obj_t * ui_SettingScreen_GpsLatitudeLabel;
extern lv_obj_t * ui_SettingScreen_GpsLatitudeMarkImage;
extern lv_obj_t * ui_SettingScreen_GpsLatitudeNextImage;
void ui_event_SettingScreen_GpsLongitudePanel(lv_event_t * e);
extern lv_obj_t * ui_SettingScreen_GpsLongitudePanel;
extern lv_obj_t * ui_SettingScreen_GpsLongitudeLabel;
extern lv_obj_t * ui_SettingScreen_GpsLongitudeMarkImage;
extern lv_obj_t * ui_SettingScreen_GpsLongitudeNextImage;
void ui_event_SettingScreen_RelayOffDelayPanel(lv_event_t * e);
extern lv_obj_t * ui_SettingScreen_RelayOffDelayPanel;
extern lv_obj_t * ui_SettingScreen_RelayOffDelayLabel;
extern lv_obj_t * ui_SettingScreen_RelayOffDelayMarkImage;
extern lv_obj_t * ui_SettingScreen_RelayOffDelayNextImage;
void ui_event_SettingScreen_RelayOnDelayPanel(lv_event_t * e);
extern lv_obj_t * ui_SettingScreen_RelayOnDelayPanel;
extern lv_obj_t * ui_SettingScreen_RelayOnDelayLabel;
extern lv_obj_t * ui_SettingScreen_RelayOnDelayMarkImage;
extern lv_obj_t * ui_SettingScreen_RelayOnDelayNextImage;
extern lv_obj_t * ui_SettingScreen_ActionPanel;
void ui_event_SettingScreen_BackButton(lv_event_t * e);
extern lv_obj_t * ui_SettingScreen_BackButton;
extern lv_obj_t * ui_SettingScreen_BackLabel;
void ui_event_SettingScreen_ResetButton(lv_event_t * e);
extern lv_obj_t * ui_SettingScreen_ResetButton;
extern lv_obj_t * ui_SettingScreen_Label6;
void ui_event_SettingScreen_ConfirmButton(lv_event_t * e);
extern lv_obj_t * ui_SettingScreen_ConfirmButton;
extern lv_obj_t * ui_SettingScreen_Label8;
// SCREEN: ui_KeyboardInputScreen
void ui_KeyboardInputScreen_screen_init(void);
extern lv_obj_t * ui_KeyboardInputScreen;
extern lv_obj_t * ui_KeyboardInputScreen_TitlePabel1;
extern lv_obj_t * ui_KeyboardInputScreen_TitleLabel;
extern lv_obj_t * ui_KeyboardInputScreen_Container3;
extern lv_obj_t * ui_KeyboardInputScreen_TextArea1;
extern lv_obj_t * ui_KeyboardInputScreen_Keyboard1;
extern lv_obj_t * ui_KeyboardInputScreen_ActionPanel1;
void ui_event_KeyboardInputScreen_BackButton1(lv_event_t * e);
extern lv_obj_t * ui_KeyboardInputScreen_BackButton1;
extern lv_obj_t * ui_KeyboardInputScreen_Label4;
void ui_event_KeyboardInputScreen_ResetButton(lv_event_t * e);
extern lv_obj_t * ui_KeyboardInputScreen_ResetButton;
extern lv_obj_t * ui_KeyboardInputScreen_Label5;
void ui_event_KeyboardInputScreen_ConfirmButton(lv_event_t * e);
extern lv_obj_t * ui_KeyboardInputScreen_ConfirmButton;
extern lv_obj_t * ui_KeyboardInputScreen_Label2;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_wifion_png);    // assets/wifion.png
LV_IMG_DECLARE(ui_img_wifioff_png);    // assets/wifioff.png
LV_IMG_DECLARE(ui_img_asterisk_png);    // assets/asterisk.png
LV_IMG_DECLARE(ui_img_caretright_png);    // assets/caretright.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
