// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: ProjectLightblub

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void toggleManualControl(lv_event_t * e);
void toggleControlOverride(lv_event_t * e);
void toOptionPage(lv_event_t * e);
void prepareWifiSSIDToInput(lv_event_t * e);
void prepareWifiPasswordToInput(lv_event_t * e);
void prepareGpsLatitudeToInput(lv_event_t * e);
void prepareGpsLongitudeToInput(lv_event_t * e);
void prepareRelayOffDelayToInput(lv_event_t * e);
void prepareRelayOnDelayToInput(lv_event_t * e);
void cancelNewSetting(lv_event_t * e);
void resetNewSettings(lv_event_t * e);
void applyNewSettings(lv_event_t * e);
void cancelCurrentInput(lv_event_t * e);
void resetCurrentInput(lv_event_t * e);
void applyCurrentInputToSetting(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
