// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: ProjectLightblub

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_blue1[1] = {0xA5F1F7};
const ui_theme_variable_t _ui_theme_alpha_blue1[1] = {255};

const ui_theme_variable_t _ui_theme_color_blue2[1] = {0x81C3D7};
const ui_theme_variable_t _ui_theme_alpha_blue2[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

