// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: ProjectLightblub

#include "../ui.h"

void ui_HomeScreen_screen_init(void)
{
    ui_HomeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HomeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_HomeScreen, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_HomeScreen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_pad_row(ui_HomeScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_HomeScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeScreen_ContentContainer = lv_obj_create(ui_HomeScreen);
    lv_obj_remove_style_all(ui_HomeScreen_ContentContainer);
    lv_obj_set_width(ui_HomeScreen_ContentContainer, lv_pct(100));
    lv_obj_set_flex_grow(ui_HomeScreen_ContentContainer, 1);
    lv_obj_set_x(ui_HomeScreen_ContentContainer, 31);
    lv_obj_set_y(ui_HomeScreen_ContentContainer, 69);
    lv_obj_set_align(ui_HomeScreen_ContentContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_HomeScreen_ContentContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_HomeScreen_ContentContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_HomeScreen_ContentContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_HomeScreen_ContentContainer, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_HomeScreen_ContentContainer, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_HomeScreen_ContentContainer, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_HomeScreen_ContentContainer, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_HomeScreen_ContentContainer, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_HomeScreen_ContentContainer, 16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeScreen_LightbulbPanel = lv_obj_create(ui_HomeScreen_ContentContainer);
    lv_obj_set_height(ui_HomeScreen_LightbulbPanel, lv_pct(100));
    lv_obj_set_flex_grow(ui_HomeScreen_LightbulbPanel, 1);
    lv_obj_set_x(ui_HomeScreen_LightbulbPanel, -103);
    lv_obj_set_y(ui_HomeScreen_LightbulbPanel, -3);
    lv_obj_set_align(ui_HomeScreen_LightbulbPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_HomeScreen_LightbulbPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_HomeScreen_LightbulbPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HomeScreen_LightbulbPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_HomeScreen_LightbulbPanel, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_HomeScreen_LightbulbPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeScreen_LightbulbLabel = lv_label_create(ui_HomeScreen_LightbulbPanel);
    lv_obj_set_width(ui_HomeScreen_LightbulbLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeScreen_LightbulbLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeScreen_LightbulbLabel, -174);
    lv_obj_set_y(ui_HomeScreen_LightbulbLabel, -122);
    lv_obj_set_align(ui_HomeScreen_LightbulbLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeScreen_LightbulbLabel, "Lightbulb");
    lv_obj_set_style_text_font(ui_HomeScreen_LightbulbLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeScreen_Container4 = lv_obj_create(ui_HomeScreen_LightbulbPanel);
    lv_obj_remove_style_all(ui_HomeScreen_Container4);
    lv_obj_set_width(ui_HomeScreen_Container4, 150);
    lv_obj_set_height(ui_HomeScreen_Container4, 60);
    lv_obj_set_align(ui_HomeScreen_Container4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HomeScreen_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HomeScreen_LightbulbStatusLed = lv_obj_create(ui_HomeScreen_Container4);
    lv_obj_set_width(ui_HomeScreen_LightbulbStatusLed, lv_pct(100));
    lv_obj_set_height(ui_HomeScreen_LightbulbStatusLed, lv_pct(100));
    lv_obj_set_align(ui_HomeScreen_LightbulbStatusLed, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HomeScreen_LightbulbStatusLed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HomeScreen_LightbulbStatusLed, 999, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HomeScreen_LightbulbStatusLed, lv_color_hex(0x12AE00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeScreen_LightbulbStatusLed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HomeScreen_LightbulbStatusLed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeScreen_LightbulbManualSwitch = lv_switch_create(ui_HomeScreen_Container4);
    lv_obj_set_width(ui_HomeScreen_LightbulbManualSwitch, lv_pct(100));
    lv_obj_set_height(ui_HomeScreen_LightbulbManualSwitch, lv_pct(100));
    lv_obj_set_align(ui_HomeScreen_LightbulbManualSwitch, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_HomeScreen_LightbulbManualSwitch, LV_STATE_FOCUSED);       /// States
    lv_obj_add_flag(ui_HomeScreen_LightbulbManualSwitch, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_HomeScreen_LightbulbManualSwitch, lv_color_hex(0xD20303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeScreen_LightbulbManualSwitch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_HomeScreen_LightbulbManualSwitch, lv_color_hex(0x12AE00),
                              LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_HomeScreen_LightbulbManualSwitch, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_HomeScreen_LightblubStateLabel = lv_label_create(ui_HomeScreen_LightbulbPanel);
    lv_obj_set_width(ui_HomeScreen_LightblubStateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeScreen_LightblubStateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeScreen_LightblubStateLabel, -174);
    lv_obj_set_y(ui_HomeScreen_LightblubStateLabel, 7);
    lv_obj_set_align(ui_HomeScreen_LightblubStateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeScreen_LightblubStateLabel, "OFF");
    lv_obj_set_style_text_font(ui_HomeScreen_LightblubStateLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeScreen_Container6 = lv_obj_create(ui_HomeScreen_ContentContainer);
    lv_obj_remove_style_all(ui_HomeScreen_Container6);
    lv_obj_set_height(ui_HomeScreen_Container6, lv_pct(100));
    lv_obj_set_width(ui_HomeScreen_Container6, LV_SIZE_CONTENT);   /// 3
    lv_obj_set_align(ui_HomeScreen_Container6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_HomeScreen_Container6, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_HomeScreen_Container6, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HomeScreen_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_HomeScreen_Container6, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_HomeScreen_Container6, 16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeScreen_TimePanel = lv_obj_create(ui_HomeScreen_Container6);
    lv_obj_set_width(ui_HomeScreen_TimePanel, 160);
    lv_obj_set_height(ui_HomeScreen_TimePanel, 84);
    lv_obj_set_x(ui_HomeScreen_TimePanel, 126);
    lv_obj_set_y(ui_HomeScreen_TimePanel, -85);
    lv_obj_set_align(ui_HomeScreen_TimePanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_HomeScreen_TimePanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_HomeScreen_TimePanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HomeScreen_TimePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HomeScreen_TimeLabel = lv_label_create(ui_HomeScreen_TimePanel);
    lv_obj_set_width(ui_HomeScreen_TimeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeScreen_TimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HomeScreen_TimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeScreen_TimeLabel, "22:00");
    lv_obj_set_style_text_font(ui_HomeScreen_TimeLabel, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeScreen_DateContainer = lv_obj_create(ui_HomeScreen_TimePanel);
    lv_obj_remove_style_all(ui_HomeScreen_DateContainer);
    lv_obj_set_width(ui_HomeScreen_DateContainer, lv_pct(100));
    lv_obj_set_height(ui_HomeScreen_DateContainer, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_HomeScreen_DateContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_HomeScreen_DateContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_HomeScreen_DateContainer, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HomeScreen_DateContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HomeScreen_WeekDayLabel = lv_label_create(ui_HomeScreen_DateContainer);
    lv_obj_set_width(ui_HomeScreen_WeekDayLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeScreen_WeekDayLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HomeScreen_WeekDayLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeScreen_WeekDayLabel, "Sun");

    ui_HomeScreen_DateLabel = lv_label_create(ui_HomeScreen_DateContainer);
    lv_obj_set_width(ui_HomeScreen_DateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeScreen_DateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HomeScreen_DateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeScreen_DateLabel, "22/10/2000");

    ui_HomeScreen_OverridePanel = lv_obj_create(ui_HomeScreen_Container6);
    lv_obj_set_width(ui_HomeScreen_OverridePanel, 160);
    lv_obj_set_flex_grow(ui_HomeScreen_OverridePanel, 1);
    lv_obj_set_x(ui_HomeScreen_OverridePanel, 126);
    lv_obj_set_y(ui_HomeScreen_OverridePanel, 41);
    lv_obj_set_align(ui_HomeScreen_OverridePanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_HomeScreen_OverridePanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_HomeScreen_OverridePanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HomeScreen_OverridePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_HomeScreen_OverridePanel, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_HomeScreen_OverridePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeScreen_OverrideLabel = lv_label_create(ui_HomeScreen_OverridePanel);
    lv_obj_set_width(ui_HomeScreen_OverrideLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeScreen_OverrideLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeScreen_OverrideLabel, 137);
    lv_obj_set_y(ui_HomeScreen_OverrideLabel, -94);
    lv_obj_set_align(ui_HomeScreen_OverrideLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeScreen_OverrideLabel, "Override");
    lv_obj_set_style_text_font(ui_HomeScreen_OverrideLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeScreen_OverrideSwitch = lv_switch_create(ui_HomeScreen_OverridePanel);
    lv_obj_set_width(ui_HomeScreen_OverrideSwitch, 120);
    lv_obj_set_height(ui_HomeScreen_OverrideSwitch, 50);
    lv_obj_set_x(ui_HomeScreen_OverrideSwitch, 138);
    lv_obj_set_y(ui_HomeScreen_OverrideSwitch, -44);
    lv_obj_set_align(ui_HomeScreen_OverrideSwitch, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_HomeScreen_OverrideSwitch, lv_color_hex(0xCBB100), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_HomeScreen_OverrideSwitch, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_HomeScreen_OverrideStateLabel = lv_label_create(ui_HomeScreen_OverridePanel);
    lv_obj_set_width(ui_HomeScreen_OverrideStateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeScreen_OverrideStateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HomeScreen_OverrideStateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeScreen_OverrideStateLabel, "OFF");
    lv_obj_set_style_text_font(ui_HomeScreen_OverrideStateLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeScreen_TitlePanel = lv_obj_create(ui_HomeScreen);
    lv_obj_set_width(ui_HomeScreen_TitlePanel, lv_pct(100));
    lv_obj_set_height(ui_HomeScreen_TitlePanel, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_HomeScreen_TitlePanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_HomeScreen_TitlePanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_HomeScreen_TitlePanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_HomeScreen_TitlePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HomeScreen_TitlePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_HomeScreen_TitlePanel, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_HomeScreen_TitlePanel, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_HomeScreen_TitlePanel, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_HomeScreen_TitlePanel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_HomeScreen_TitlePanel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeScreen_WifiStatusContainer = lv_obj_create(ui_HomeScreen_TitlePanel);
    lv_obj_remove_style_all(ui_HomeScreen_WifiStatusContainer);
    lv_obj_set_width(ui_HomeScreen_WifiStatusContainer, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_HomeScreen_WifiStatusContainer, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_HomeScreen_WifiStatusContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HomeScreen_WifiStatusContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HomeScreen_WifiOnImage = lv_img_create(ui_HomeScreen_WifiStatusContainer);
    lv_img_set_src(ui_HomeScreen_WifiOnImage, &ui_img_wifion_png);
    lv_obj_set_width(ui_HomeScreen_WifiOnImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeScreen_WifiOnImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HomeScreen_WifiOnImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeScreen_WifiOnImage, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HomeScreen_WifiOnImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HomeScreen_WifiOffImage = lv_img_create(ui_HomeScreen_WifiStatusContainer);
    lv_img_set_src(ui_HomeScreen_WifiOffImage, &ui_img_wifioff_png);
    lv_obj_set_width(ui_HomeScreen_WifiOffImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeScreen_WifiOffImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HomeScreen_WifiOffImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeScreen_WifiOffImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HomeScreen_WifiOffImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HomeScreen_TitleLabel = lv_label_create(ui_HomeScreen_TitlePanel);
    lv_obj_set_height(ui_HomeScreen_TitleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_HomeScreen_TitleLabel, 1);
    lv_obj_set_align(ui_HomeScreen_TitleLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeScreen_TitleLabel, "Project Lightbulb 1.0");
    lv_obj_set_style_text_font(ui_HomeScreen_TitleLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeScreen_OptionButton = lv_btn_create(ui_HomeScreen_TitlePanel);
    lv_obj_set_width(ui_HomeScreen_OptionButton, 100);
    lv_obj_set_height(ui_HomeScreen_OptionButton, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_HomeScreen_OptionButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeScreen_OptionButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HomeScreen_OptionButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HomeScreen_OptionLabel = lv_label_create(ui_HomeScreen_OptionButton);
    lv_obj_set_width(ui_HomeScreen_OptionLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeScreen_OptionLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HomeScreen_OptionLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeScreen_OptionLabel, "Option");

    lv_obj_add_event_cb(ui_HomeScreen_LightbulbManualSwitch, ui_event_HomeScreen_LightbulbManualSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HomeScreen_OverrideSwitch, ui_event_HomeScreen_OverrideSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HomeScreen_OptionButton, ui_event_HomeScreen_OptionButton, LV_EVENT_ALL, NULL);

}
