// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: ProjectLightblub

#include "../ui.h"

void ui_KeyboardInputScreen_screen_init(void)
{
    ui_KeyboardInputScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_KeyboardInputScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_KeyboardInputScreen, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_KeyboardInputScreen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_pad_row(ui_KeyboardInputScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_KeyboardInputScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KeyboardInputScreen_TitlePabel1 = lv_obj_create(ui_KeyboardInputScreen);
    lv_obj_set_width(ui_KeyboardInputScreen_TitlePabel1, lv_pct(100));
    lv_obj_set_height(ui_KeyboardInputScreen_TitlePabel1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_KeyboardInputScreen_TitlePabel1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_KeyboardInputScreen_TitlePabel1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_KeyboardInputScreen_TitlePabel1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_KeyboardInputScreen_TitlePabel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_KeyboardInputScreen_TitlePabel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_KeyboardInputScreen_TitlePabel1, LV_BORDER_SIDE_BOTTOM,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_KeyboardInputScreen_TitlePabel1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_KeyboardInputScreen_TitlePabel1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_KeyboardInputScreen_TitlePabel1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_KeyboardInputScreen_TitlePabel1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KeyboardInputScreen_TitleLabel = lv_label_create(ui_KeyboardInputScreen_TitlePabel1);
    lv_obj_set_width(ui_KeyboardInputScreen_TitleLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_KeyboardInputScreen_TitleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_KeyboardInputScreen_TitleLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_KeyboardInputScreen_TitleLabel, "Input");
    lv_obj_set_style_text_font(ui_KeyboardInputScreen_TitleLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KeyboardInputScreen_Container3 = lv_obj_create(ui_KeyboardInputScreen);
    lv_obj_remove_style_all(ui_KeyboardInputScreen_Container3);
    lv_obj_set_width(ui_KeyboardInputScreen_Container3, lv_pct(100));
    lv_obj_set_flex_grow(ui_KeyboardInputScreen_Container3, 1);
    lv_obj_set_x(ui_KeyboardInputScreen_Container3, 31);
    lv_obj_set_y(ui_KeyboardInputScreen_Container3, 69);
    lv_obj_set_align(ui_KeyboardInputScreen_Container3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_KeyboardInputScreen_Container3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_KeyboardInputScreen_Container3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_KeyboardInputScreen_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_KeyboardInputScreen_Container3, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_KeyboardInputScreen_Container3, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_KeyboardInputScreen_Container3, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_KeyboardInputScreen_Container3, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_KeyboardInputScreen_Container3, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_KeyboardInputScreen_Container3, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KeyboardInputScreen_TextArea1 = lv_textarea_create(ui_KeyboardInputScreen_Container3);
    lv_obj_set_width(ui_KeyboardInputScreen_TextArea1, lv_pct(100));
    lv_obj_set_height(ui_KeyboardInputScreen_TextArea1, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_align(ui_KeyboardInputScreen_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_KeyboardInputScreen_TextArea1, "Placeholder...");
    lv_textarea_set_one_line(ui_KeyboardInputScreen_TextArea1, true);
    lv_obj_set_style_pad_left(ui_KeyboardInputScreen_TextArea1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_KeyboardInputScreen_TextArea1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_KeyboardInputScreen_TextArea1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_KeyboardInputScreen_TextArea1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_KeyboardInputScreen_Keyboard1 = lv_keyboard_create(ui_KeyboardInputScreen_Container3);
    lv_obj_set_width(ui_KeyboardInputScreen_Keyboard1, lv_pct(100));
    lv_obj_set_flex_grow(ui_KeyboardInputScreen_Keyboard1, 1);
    lv_obj_set_align(ui_KeyboardInputScreen_Keyboard1, LV_ALIGN_CENTER);

    ui_KeyboardInputScreen_ActionPanel1 = lv_obj_create(ui_KeyboardInputScreen);
    lv_obj_set_width(ui_KeyboardInputScreen_ActionPanel1, lv_pct(100));
    lv_obj_set_height(ui_KeyboardInputScreen_ActionPanel1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_KeyboardInputScreen_ActionPanel1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_KeyboardInputScreen_ActionPanel1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_KeyboardInputScreen_ActionPanel1, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_KeyboardInputScreen_ActionPanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_KeyboardInputScreen_ActionPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_KeyboardInputScreen_ActionPanel1, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_KeyboardInputScreen_ActionPanel1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_KeyboardInputScreen_ActionPanel1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_KeyboardInputScreen_ActionPanel1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_KeyboardInputScreen_ActionPanel1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KeyboardInputScreen_BackButton1 = lv_btn_create(ui_KeyboardInputScreen_ActionPanel1);
    lv_obj_set_width(ui_KeyboardInputScreen_BackButton1, 100);
    lv_obj_set_height(ui_KeyboardInputScreen_BackButton1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_KeyboardInputScreen_BackButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_KeyboardInputScreen_BackButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_KeyboardInputScreen_BackButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_KeyboardInputScreen_Label4 = lv_label_create(ui_KeyboardInputScreen_BackButton1);
    lv_obj_set_width(ui_KeyboardInputScreen_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_KeyboardInputScreen_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_KeyboardInputScreen_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_KeyboardInputScreen_Label4, "Cancel");

    ui_KeyboardInputScreen_ResetButton = lv_btn_create(ui_KeyboardInputScreen_ActionPanel1);
    lv_obj_set_width(ui_KeyboardInputScreen_ResetButton, 100);
    lv_obj_set_height(ui_KeyboardInputScreen_ResetButton, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_KeyboardInputScreen_ResetButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_KeyboardInputScreen_ResetButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_KeyboardInputScreen_ResetButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_KeyboardInputScreen_ResetButton, lv_color_hex(0xD75C5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_KeyboardInputScreen_ResetButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KeyboardInputScreen_Label5 = lv_label_create(ui_KeyboardInputScreen_ResetButton);
    lv_obj_set_width(ui_KeyboardInputScreen_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_KeyboardInputScreen_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_KeyboardInputScreen_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_KeyboardInputScreen_Label5, "Reset");

    ui_KeyboardInputScreen_ConfirmButton = lv_btn_create(ui_KeyboardInputScreen_ActionPanel1);
    lv_obj_set_width(ui_KeyboardInputScreen_ConfirmButton, 100);
    lv_obj_set_height(ui_KeyboardInputScreen_ConfirmButton, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_KeyboardInputScreen_ConfirmButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_KeyboardInputScreen_ConfirmButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_KeyboardInputScreen_ConfirmButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_KeyboardInputScreen_Label2 = lv_label_create(ui_KeyboardInputScreen_ConfirmButton);
    lv_obj_set_width(ui_KeyboardInputScreen_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_KeyboardInputScreen_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_KeyboardInputScreen_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_KeyboardInputScreen_Label2, "Confirm");

    lv_keyboard_set_textarea(ui_KeyboardInputScreen_Keyboard1, ui_KeyboardInputScreen_TextArea1);
    lv_obj_add_event_cb(ui_KeyboardInputScreen_BackButton1, ui_event_KeyboardInputScreen_BackButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_KeyboardInputScreen_ResetButton, ui_event_KeyboardInputScreen_ResetButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_KeyboardInputScreen_ConfirmButton, ui_event_KeyboardInputScreen_ConfirmButton, LV_EVENT_ALL,
                        NULL);

}
