// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: ProjectLightblub

#include "../ui.h"

void ui_SettingScreen_screen_init(void)
{
    ui_SettingScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SettingScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_SettingScreen, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_SettingScreen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_pad_row(ui_SettingScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_SettingScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingScreen_TitlePabel = lv_obj_create(ui_SettingScreen);
    lv_obj_set_width(ui_SettingScreen_TitlePabel, lv_pct(100));
    lv_obj_set_height(ui_SettingScreen_TitlePabel, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_SettingScreen_TitlePabel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SettingScreen_TitlePabel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_SettingScreen_TitlePabel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_SettingScreen_TitlePabel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SettingScreen_TitlePabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_SettingScreen_TitlePabel, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SettingScreen_TitlePabel, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SettingScreen_TitlePabel, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SettingScreen_TitlePabel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SettingScreen_TitlePabel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingScreen_TitleLabel = lv_label_create(ui_SettingScreen_TitlePabel);
    lv_obj_set_width(ui_SettingScreen_TitleLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingScreen_TitleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingScreen_TitleLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingScreen_TitleLabel, "Setting");
    lv_obj_set_style_text_font(ui_SettingScreen_TitleLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingScreen_ContentContainer = lv_obj_create(ui_SettingScreen);
    lv_obj_remove_style_all(ui_SettingScreen_ContentContainer);
    lv_obj_set_width(ui_SettingScreen_ContentContainer, lv_pct(100));
    lv_obj_set_flex_grow(ui_SettingScreen_ContentContainer, 1);
    lv_obj_set_x(ui_SettingScreen_ContentContainer, 31);
    lv_obj_set_y(ui_SettingScreen_ContentContainer, 69);
    lv_obj_set_align(ui_SettingScreen_ContentContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SettingScreen_ContentContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_SettingScreen_ContentContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_SettingScreen_ContentContainer, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_scroll_dir(ui_SettingScreen_ContentContainer, LV_DIR_VER);
    lv_obj_set_style_pad_left(ui_SettingScreen_ContentContainer, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SettingScreen_ContentContainer, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SettingScreen_ContentContainer, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SettingScreen_ContentContainer, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_SettingScreen_ContentContainer, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_SettingScreen_ContentContainer, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingScreen_WifiSSIDPanel = lv_obj_create(ui_SettingScreen_ContentContainer);
    lv_obj_set_width(ui_SettingScreen_WifiSSIDPanel, lv_pct(100));
    lv_obj_set_height(ui_SettingScreen_WifiSSIDPanel, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_SettingScreen_WifiSSIDPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SettingScreen_WifiSSIDPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_SettingScreen_WifiSSIDPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SettingScreen_WifiSSIDPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_SettingScreen_WifiSSIDPanel, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SettingScreen_WifiSSIDPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SettingScreen_WifiSSIDPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SettingScreen_WifiSSIDPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingScreen_WifiSSIDLabel = lv_label_create(ui_SettingScreen_WifiSSIDPanel);
    lv_obj_set_height(ui_SettingScreen_WifiSSIDLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_SettingScreen_WifiSSIDLabel, 1);
    lv_obj_set_align(ui_SettingScreen_WifiSSIDLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingScreen_WifiSSIDLabel, "WIFI SSID");
    lv_label_set_recolor(ui_SettingScreen_WifiSSIDLabel, "true");

    ui_SettingScreen_WifiSSIDMarkImage = lv_img_create(ui_SettingScreen_WifiSSIDPanel);
    lv_img_set_src(ui_SettingScreen_WifiSSIDMarkImage, &ui_img_asterisk_png);
    lv_obj_set_width(ui_SettingScreen_WifiSSIDMarkImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingScreen_WifiSSIDMarkImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingScreen_WifiSSIDMarkImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingScreen_WifiSSIDMarkImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SettingScreen_WifiSSIDMarkImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingScreen_WifiSSIDNextImage = lv_img_create(ui_SettingScreen_WifiSSIDPanel);
    lv_img_set_src(ui_SettingScreen_WifiSSIDNextImage, &ui_img_caretright_png);
    lv_obj_set_width(ui_SettingScreen_WifiSSIDNextImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingScreen_WifiSSIDNextImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingScreen_WifiSSIDNextImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingScreen_WifiSSIDNextImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SettingScreen_WifiSSIDNextImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingScreen_WifiPasswordPanel = lv_obj_create(ui_SettingScreen_ContentContainer);
    lv_obj_set_width(ui_SettingScreen_WifiPasswordPanel, lv_pct(100));
    lv_obj_set_height(ui_SettingScreen_WifiPasswordPanel, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_SettingScreen_WifiPasswordPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SettingScreen_WifiPasswordPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_SettingScreen_WifiPasswordPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SettingScreen_WifiPasswordPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_SettingScreen_WifiPasswordPanel, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SettingScreen_WifiPasswordPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SettingScreen_WifiPasswordPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SettingScreen_WifiPasswordPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingScreen_WifiPasswordLabel = lv_label_create(ui_SettingScreen_WifiPasswordPanel);
    lv_obj_set_height(ui_SettingScreen_WifiPasswordLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_SettingScreen_WifiPasswordLabel, 1);
    lv_obj_set_align(ui_SettingScreen_WifiPasswordLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingScreen_WifiPasswordLabel, "WIFI Password");
    lv_label_set_recolor(ui_SettingScreen_WifiPasswordLabel, "true");

    ui_SettingScreen_WifiPasswordMarkImage = lv_img_create(ui_SettingScreen_WifiPasswordPanel);
    lv_img_set_src(ui_SettingScreen_WifiPasswordMarkImage, &ui_img_asterisk_png);
    lv_obj_set_width(ui_SettingScreen_WifiPasswordMarkImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingScreen_WifiPasswordMarkImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingScreen_WifiPasswordMarkImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingScreen_WifiPasswordMarkImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SettingScreen_WifiPasswordMarkImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingScreen_WifiPasswordNextImage = lv_img_create(ui_SettingScreen_WifiPasswordPanel);
    lv_img_set_src(ui_SettingScreen_WifiPasswordNextImage, &ui_img_caretright_png);
    lv_obj_set_width(ui_SettingScreen_WifiPasswordNextImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingScreen_WifiPasswordNextImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingScreen_WifiPasswordNextImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingScreen_WifiPasswordNextImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SettingScreen_WifiPasswordNextImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingScreen_GpsLatitudePanel = lv_obj_create(ui_SettingScreen_ContentContainer);
    lv_obj_set_width(ui_SettingScreen_GpsLatitudePanel, lv_pct(100));
    lv_obj_set_height(ui_SettingScreen_GpsLatitudePanel, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_SettingScreen_GpsLatitudePanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SettingScreen_GpsLatitudePanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_SettingScreen_GpsLatitudePanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SettingScreen_GpsLatitudePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_SettingScreen_GpsLatitudePanel, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SettingScreen_GpsLatitudePanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SettingScreen_GpsLatitudePanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SettingScreen_GpsLatitudePanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingScreen_GpsLatitudeLabel = lv_label_create(ui_SettingScreen_GpsLatitudePanel);
    lv_obj_set_height(ui_SettingScreen_GpsLatitudeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_SettingScreen_GpsLatitudeLabel, 1);
    lv_obj_set_align(ui_SettingScreen_GpsLatitudeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingScreen_GpsLatitudeLabel, "GPS Latitude");
    lv_label_set_recolor(ui_SettingScreen_GpsLatitudeLabel, "true");

    ui_SettingScreen_GpsLatitudeMarkImage = lv_img_create(ui_SettingScreen_GpsLatitudePanel);
    lv_img_set_src(ui_SettingScreen_GpsLatitudeMarkImage, &ui_img_asterisk_png);
    lv_obj_set_width(ui_SettingScreen_GpsLatitudeMarkImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingScreen_GpsLatitudeMarkImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingScreen_GpsLatitudeMarkImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingScreen_GpsLatitudeMarkImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SettingScreen_GpsLatitudeMarkImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingScreen_GpsLatitudeNextImage = lv_img_create(ui_SettingScreen_GpsLatitudePanel);
    lv_img_set_src(ui_SettingScreen_GpsLatitudeNextImage, &ui_img_caretright_png);
    lv_obj_set_width(ui_SettingScreen_GpsLatitudeNextImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingScreen_GpsLatitudeNextImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingScreen_GpsLatitudeNextImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingScreen_GpsLatitudeNextImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SettingScreen_GpsLatitudeNextImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingScreen_GpsLongitudePanel = lv_obj_create(ui_SettingScreen_ContentContainer);
    lv_obj_set_width(ui_SettingScreen_GpsLongitudePanel, lv_pct(100));
    lv_obj_set_height(ui_SettingScreen_GpsLongitudePanel, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_SettingScreen_GpsLongitudePanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SettingScreen_GpsLongitudePanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_SettingScreen_GpsLongitudePanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SettingScreen_GpsLongitudePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_SettingScreen_GpsLongitudePanel, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SettingScreen_GpsLongitudePanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SettingScreen_GpsLongitudePanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SettingScreen_GpsLongitudePanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingScreen_GpsLongitudeLabel = lv_label_create(ui_SettingScreen_GpsLongitudePanel);
    lv_obj_set_height(ui_SettingScreen_GpsLongitudeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_SettingScreen_GpsLongitudeLabel, 1);
    lv_obj_set_align(ui_SettingScreen_GpsLongitudeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingScreen_GpsLongitudeLabel, "GPS Longitude");
    lv_label_set_recolor(ui_SettingScreen_GpsLongitudeLabel, "true");

    ui_SettingScreen_GpsLongitudeMarkImage = lv_img_create(ui_SettingScreen_GpsLongitudePanel);
    lv_img_set_src(ui_SettingScreen_GpsLongitudeMarkImage, &ui_img_asterisk_png);
    lv_obj_set_width(ui_SettingScreen_GpsLongitudeMarkImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingScreen_GpsLongitudeMarkImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingScreen_GpsLongitudeMarkImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingScreen_GpsLongitudeMarkImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SettingScreen_GpsLongitudeMarkImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingScreen_GpsLongitudeNextImage = lv_img_create(ui_SettingScreen_GpsLongitudePanel);
    lv_img_set_src(ui_SettingScreen_GpsLongitudeNextImage, &ui_img_caretright_png);
    lv_obj_set_width(ui_SettingScreen_GpsLongitudeNextImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingScreen_GpsLongitudeNextImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingScreen_GpsLongitudeNextImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingScreen_GpsLongitudeNextImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SettingScreen_GpsLongitudeNextImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingScreen_RelayOffDelayPanel = lv_obj_create(ui_SettingScreen_ContentContainer);
    lv_obj_set_width(ui_SettingScreen_RelayOffDelayPanel, lv_pct(100));
    lv_obj_set_height(ui_SettingScreen_RelayOffDelayPanel, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_SettingScreen_RelayOffDelayPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SettingScreen_RelayOffDelayPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_SettingScreen_RelayOffDelayPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SettingScreen_RelayOffDelayPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_SettingScreen_RelayOffDelayPanel, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SettingScreen_RelayOffDelayPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SettingScreen_RelayOffDelayPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SettingScreen_RelayOffDelayPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingScreen_RelayOffDelayLabel = lv_label_create(ui_SettingScreen_RelayOffDelayPanel);
    lv_obj_set_height(ui_SettingScreen_RelayOffDelayLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_SettingScreen_RelayOffDelayLabel, 1);
    lv_obj_set_align(ui_SettingScreen_RelayOffDelayLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingScreen_RelayOffDelayLabel, "Sunrise Relay Off Delay");
    lv_label_set_recolor(ui_SettingScreen_RelayOffDelayLabel, "true");

    ui_SettingScreen_RelayOffDelayMarkImage = lv_img_create(ui_SettingScreen_RelayOffDelayPanel);
    lv_img_set_src(ui_SettingScreen_RelayOffDelayMarkImage, &ui_img_asterisk_png);
    lv_obj_set_width(ui_SettingScreen_RelayOffDelayMarkImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingScreen_RelayOffDelayMarkImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingScreen_RelayOffDelayMarkImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingScreen_RelayOffDelayMarkImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SettingScreen_RelayOffDelayMarkImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingScreen_RelayOffDelayNextImage = lv_img_create(ui_SettingScreen_RelayOffDelayPanel);
    lv_img_set_src(ui_SettingScreen_RelayOffDelayNextImage, &ui_img_caretright_png);
    lv_obj_set_width(ui_SettingScreen_RelayOffDelayNextImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingScreen_RelayOffDelayNextImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingScreen_RelayOffDelayNextImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingScreen_RelayOffDelayNextImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SettingScreen_RelayOffDelayNextImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingScreen_RelayOnDelayPanel = lv_obj_create(ui_SettingScreen_ContentContainer);
    lv_obj_set_width(ui_SettingScreen_RelayOnDelayPanel, lv_pct(100));
    lv_obj_set_height(ui_SettingScreen_RelayOnDelayPanel, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_SettingScreen_RelayOnDelayPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SettingScreen_RelayOnDelayPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_SettingScreen_RelayOnDelayPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SettingScreen_RelayOnDelayPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_SettingScreen_RelayOnDelayPanel, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SettingScreen_RelayOnDelayPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SettingScreen_RelayOnDelayPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SettingScreen_RelayOnDelayPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingScreen_RelayOnDelayLabel = lv_label_create(ui_SettingScreen_RelayOnDelayPanel);
    lv_obj_set_height(ui_SettingScreen_RelayOnDelayLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(ui_SettingScreen_RelayOnDelayLabel, 1);
    lv_obj_set_align(ui_SettingScreen_RelayOnDelayLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingScreen_RelayOnDelayLabel, "Sunset Relay On Delay");
    lv_label_set_recolor(ui_SettingScreen_RelayOnDelayLabel, "true");

    ui_SettingScreen_RelayOnDelayMarkImage = lv_img_create(ui_SettingScreen_RelayOnDelayPanel);
    lv_img_set_src(ui_SettingScreen_RelayOnDelayMarkImage, &ui_img_asterisk_png);
    lv_obj_set_width(ui_SettingScreen_RelayOnDelayMarkImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingScreen_RelayOnDelayMarkImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingScreen_RelayOnDelayMarkImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingScreen_RelayOnDelayMarkImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SettingScreen_RelayOnDelayMarkImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingScreen_RelayOnDelayNextImage = lv_img_create(ui_SettingScreen_RelayOnDelayPanel);
    lv_img_set_src(ui_SettingScreen_RelayOnDelayNextImage, &ui_img_caretright_png);
    lv_obj_set_width(ui_SettingScreen_RelayOnDelayNextImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingScreen_RelayOnDelayNextImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingScreen_RelayOnDelayNextImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingScreen_RelayOnDelayNextImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SettingScreen_RelayOnDelayNextImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingScreen_ActionPanel = lv_obj_create(ui_SettingScreen);
    lv_obj_set_width(ui_SettingScreen_ActionPanel, lv_pct(100));
    lv_obj_set_height(ui_SettingScreen_ActionPanel, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_SettingScreen_ActionPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SettingScreen_ActionPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_SettingScreen_ActionPanel, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_SettingScreen_ActionPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SettingScreen_ActionPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_SettingScreen_ActionPanel, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SettingScreen_ActionPanel, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SettingScreen_ActionPanel, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SettingScreen_ActionPanel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SettingScreen_ActionPanel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingScreen_BackButton = lv_btn_create(ui_SettingScreen_ActionPanel);
    lv_obj_set_width(ui_SettingScreen_BackButton, 100);
    lv_obj_set_height(ui_SettingScreen_BackButton, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_SettingScreen_BackButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingScreen_BackButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SettingScreen_BackButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingScreen_BackLabel = lv_label_create(ui_SettingScreen_BackButton);
    lv_obj_set_width(ui_SettingScreen_BackLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingScreen_BackLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingScreen_BackLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingScreen_BackLabel, "Cancel");

    ui_SettingScreen_ResetButton = lv_btn_create(ui_SettingScreen_ActionPanel);
    lv_obj_set_width(ui_SettingScreen_ResetButton, 100);
    lv_obj_set_height(ui_SettingScreen_ResetButton, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_SettingScreen_ResetButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingScreen_ResetButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SettingScreen_ResetButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SettingScreen_ResetButton, lv_color_hex(0xD75C5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingScreen_ResetButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingScreen_Label6 = lv_label_create(ui_SettingScreen_ResetButton);
    lv_obj_set_width(ui_SettingScreen_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingScreen_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingScreen_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingScreen_Label6, "Reset");

    ui_SettingScreen_ConfirmButton = lv_btn_create(ui_SettingScreen_ActionPanel);
    lv_obj_set_width(ui_SettingScreen_ConfirmButton, 100);
    lv_obj_set_height(ui_SettingScreen_ConfirmButton, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_SettingScreen_ConfirmButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingScreen_ConfirmButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SettingScreen_ConfirmButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingScreen_Label8 = lv_label_create(ui_SettingScreen_ConfirmButton);
    lv_obj_set_width(ui_SettingScreen_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingScreen_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingScreen_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingScreen_Label8, "Confirm");

    lv_obj_add_event_cb(ui_SettingScreen_WifiSSIDPanel, ui_event_SettingScreen_WifiSSIDPanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SettingScreen_WifiPasswordPanel, ui_event_SettingScreen_WifiPasswordPanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SettingScreen_GpsLatitudePanel, ui_event_SettingScreen_GpsLatitudePanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SettingScreen_GpsLongitudePanel, ui_event_SettingScreen_GpsLongitudePanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SettingScreen_RelayOffDelayPanel, ui_event_SettingScreen_RelayOffDelayPanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SettingScreen_RelayOnDelayPanel, ui_event_SettingScreen_RelayOnDelayPanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SettingScreen_BackButton, ui_event_SettingScreen_BackButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SettingScreen_ResetButton, ui_event_SettingScreen_ResetButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SettingScreen_ConfirmButton, ui_event_SettingScreen_ConfirmButton, LV_EVENT_ALL, NULL);

}
